{{ $architecture := or .architecture "arm64" }}
{{ $image := or .image "xen-boot" }}

architecture: {{ $architecture }}

{{ $size := or .size "2G" }}
{{ $ptype := or .ptype "msdos" }}

actions:
  - action: image-partition
    imagename: {{ $image }}.img
    imagesize: {{ $size }}
    partitiontype: {{ $ptype }}
    partitions:
      - name: boot
        fs: vfat
        start: 0%
        end: 1G

    
