{{ $architecture := or .architecture "arm64" }}
{{ $image := or .image "xen-demo" }}

architecture: {{ $architecture }}

{{ $size := or .size "8589934592B" }}
{{ $ptype := or .ptype "msdos" }}

actions:
  - action: image-partition
    imagename: {{ $image }}.img
    imagesize: {{ $size }}
    partitiontype: {{ $ptype }}
    partitions:
      - name: boot
        fs: vfat
        start: 0%
        end: 1G
      - name: system
        fs: ext4
        start: 2G
        end: 4G
      - name: system2
        fs: ext4
        start: 4G
        end: 100%

    
