{{ $architecture := or .architecture "arm64" }}
{{ $image := or .image "xen-demo" }}

architecture: {{ $architecture }}

{{ $size := or .size "6G" }}
{{ $ptype := or .ptype "msdos" }}

actions:
  - action: image-partition
    imagename: {{ $image }}.img
    imagesize: {{ $size }}
    partitiontype: {{ $ptype }}
    partitions:
      - name: firmware
        fs: vfat
        start: 0%
        end: 1G
      - name: system
        fs: ext4
        start: 1G
        end: 3G
      - name: system2
        fs: ext4
        start: 3G
        end: 100%

    
